name ='The MaxJ-L Stack'
baseURL = "https://MaxJ-L.github.io/"
languageCode = 'zh-CN'
theme = 'PaperMod'
title = 'The MaxJ-L Stack'

[outputs]
  home = ["HTML", "RSS", "JSON"]

  # -- 导航栏菜单配置 --
[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/" # 链接到我们刚刚创建的 archives.md
  weight = 10 # 权重，数字越小越靠前

[[menu.main]]
  identifier = "search"
  name = "搜索"
  url = "/search/"
  weight = 20

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 30
